### ISSUE TITLE
Handle Startup ctor exceptions better in the Visual Studio debugger.

### ISSUE THREAD

**Issue by burtonrodman** [aspnet/Tooling#167]
When the Startup class constructor throws an exception, the only information available in Visual Studio's default debugging config is a TargetInvocationException with zero useful callstack info:

System.Reflection.TargetInvocationException was unhandled
Message: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Additional information: Exception has been thrown by the target of an invocation.

Even stepping through the constructor (without a try/catch) leads to the TargetInvocationException MDA instead of (in my case) the actual exception which was as FileNotFoundException from a call to AddJsonFile with the optional flag set to false.

Running dnx . web from a command line gives the proper exception information, but many devs (including myself) might not think to do this until we've wasted much time finding the root cause.

**Comment by sayedihashimi** [comment]
TFS: 149358
I've added it to our TFS bug tracker, will reply back here soon.

**Comment by sayedihashimi** [comment]
Hi @burtonrodman can you try this with [beta8](http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx)? I think this should be fixed but I'm not 100% sure.

**Comment by burtonrodman** [comment]
Was planning to update my project to beta8 this weekend.  Will try it out and let you know.

**Comment by burtonrodman** [comment]
this situation is improved.  Now when just hitting F5, you still get a 500 message in the browser with Kestrel.  If you place a breakpoint in the StartUp class constructor, and step to the exception, the dnx.exe command line window is activated and you get a callstack dump showing the FileNotFoundException.  If you then enable first-chance handling on FileNotFoundException and step through you get an MDA for FileNotFoundException with the appropriate path specified, instead of TypeInvocationException.
