### ISSUE TITLE
VS2015 build give an error about missing namespace in output window but no errors in 'error list' window

### ISSUE THREAD

**Issue by Anderman** [aspnet/Tooling#175]
output window give this error:
`C:\git\DBC\src\DBC\Controllers\UserController.cs(77,24): DNX,Version=v4.5.1 error CS0118: 'DataTables' is a namespace but is used like a type`

for this line
```
            return new DataTables().GetJSonResult(
                z
                , dTRequest);
```
This can be fixed with adding a namespace
```
            return new Mvc.JQuery.Datatables.DataTables().GetJSonResult(
                z
                , dTRequest);

```
but 'error list' window show no errors

![image](https://cloud.githubusercontent.com/assets/1858745/9808807/f8255c48-5862-11e5-8504-0084d25d29f7.png)

![image](https://cloud.githubusercontent.com/assets/1858745/9808814/079526ae-5863-11e5-9fc1-b65b9b407990.png)

This issue is in  my repro see the commits in [DBC](https://github.com/Medella/DBC/commits/master) 
`3cedf0de134730f7213f756b5ed650acb45ee8fc`
and
'a16136000372649505e7aff36bd025c6d3234a1d'

**Comment by sayedihashimi** [comment]
Adding @BillHiebert

**Comment by BillHiebert** [comment]
@Anderman 
Can you upgrade to the RTM version? There were lots of fixes between RC and RTM though I don't know if this particular issue was fixed or not.

**Comment by Anderman** [comment]
This is mine version. I am not sure if this is RC or RTM
```Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA273
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA273
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA273
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA273
Microsoft Visual C++ 2015

.NET Reflector Visual Studio Extension   8.5.0.179
Integrates .NET Reflector into Visual Studio to allow you to seamlessly debug into third-party code and assemblies, even if you don't have the source code for them.

Visit www.reflector.net for more information.

Copyright (c) 2009-2012 Red Gate Software Inc.

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (Beta7)   14.0.60831.0
ASP.NET and Web Tools 2015 (Beta7)

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JetBrains ReSharper Ultimate 2015.1.1   Build 102.0.20150521.123255
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2015 JetBrains, Inc.

Microsoft Azure HDInsight HQL Service   2.0.2200.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2200.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30728.1602

Microsoft Code Digger   0.9
Microsoft Code Digger

Microsoft.Pex.VisualStudio   1.0
Pex

NuGet Package Manager   3.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   1.6
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.```

**Comment by sayedihashimi** [comment]
TFS:149252
@Anderman that looks like RTM to me. I've added it to our internal bug tracker, will reply soon.

**Comment by BillHiebert** [comment]
I am pretty sure we fixed this in either beta6 or beta7. We made a bunch of changes to our error list handling.

**Comment by sayedihashimi** [comment]
@Anderman can you try with beta7 http://blogs.msdn.com/b/webdev/archive/2015/09/02/announcing-availability-of-asp-net-5-beta7.aspx? We think this has been fixed.

**Comment by Anderman** [comment]
This error was with beta 7. 
I just tried this and t still the same
My global.json
```
{
  "projects": [
    "src",
    "test",
    "../TagHelpers/src",
    "../Mvc.JQuery.Datatables/src",
    "wrap"
  ],
  "sdk": {
    "version": "1.0.0-beta7"
  }
}
```
![image](https://cloud.githubusercontent.com/assets/1858745/10178594/0223e366-6701-11e5-9ae7-6d3d025eb7ac.png)
![image](https://cloud.githubusercontent.com/assets/1858745/10178677/82c3773e-6701-11e5-847a-115a7c9d3540.png)


Do I need something else to install or update?

**Comment by sayedihashimi** [comment]
TFS:149635
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
This should be fixed in beta8 which you can get at http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx. I'll close this now, but if you are still facing this with beta8 please reopen this.
