### ISSUE TITLE
Does not play nice with NPM v3

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Tooling#197]
NPM v3 installs dependencies in as flat a manner as possible. This is great for the sake of NPM, especially on Windows with the whole 'long filename' thing. This is not so great for the current implementation of the Visual Studio tooling, because it now lists out the hundreds of flattened dependencies with "extraneous" tacked on the end rather than listing a tree starting from the top-level dependencies  (`npm list` still spits out such a tree.)

**Comment by sayedihashimi** [comment]
Adding @madskristensen to reply back

**Comment by madskristensen** [comment]
This is being fixed now

**Comment by tuespetre** [comment]
Thank you both!

**Comment by MartinJohns** [comment]
@madskristensen Hey Mads,

Can you please say with what update it is being fixed? The problem still occurs with VS2015 Update 1 RC, as well as with ASP.NET 5 tooling RC1.

Might be nice to keep the issue open until it is actually fixed and available for the masses.

**Comment by madskristensen** [comment]
Should be in the final RTM of Update 1 but haven't checked since I've been on paternity leave the last 4 weeks. I'm installing latest bits now to verify...

**Comment by MartinJohns** [comment]
Hello @madskristensen,

Unfortunately this is not fixed as part of VS2015 Update 1 final. I installed it, but it still displays a lot of packages as "extraneous".

**Comment by MartinJohns** [comment]
I just verified it, it's still not working

- Microsoft visual Studio Community 2015 Version 14.0.24720.00 Update 1
- ASP.NET and Web Tools 2015 (RC1 Update 1) 14.1.11120.0

**Comment by MartinJohns** [comment]
@madskristensen ?

**Comment by madskristensen** [comment]
Update 2 is when the fix lands
