### ISSUE TITLE
nesting files inside solution explorer

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#423]
Hi,
  It's possible to add a nesting rule that nests <filename>.d.ts under <filename> please? 
  I'm using web essentials to create typescript intellisense files based on c# classes and I have this: 

![untitled2](https://cloud.githubusercontent.com/assets/127777/13708594/ce521f96-e7af-11e5-9f0c-31f77d5b4efc.png)

  when the .d.ts file is created or modified it's shown as dependent from the cs file, but if I close and reopen the project it is shown as indipendent.

**Comment by oising** [comment]
https://visualstudiogallery.msdn.microsoft.com/3ebde8fb-26d8-4374-a0eb-1e4e2665070c

**Comment by lucamorelli** [comment]
I think that extension doesn't work with an asp.net 5 project, because it's based on writing the relationship between the file inside the msbuild project. I have this extension installed but is not even shown inside an asp.net 5 project

**Comment by sayedihashimi** [comment]
TFS: 203552
I've added this to our internal TFS, we will reply back here soon.

Thanks. On the backlog we have an item to support customizing the nesting in general. We are working on some other high priority items so we have not started that work yet. In the mean time, I've filed a bug internally to create a specific nesting rule for this scenario.

**Comment by abpiskunov** [comment]
This is resolved in RC2

**Comment by ZoolWay** [comment]
Is there any update on nesting configuration?

Unfortunately the extension "File Nesting" (mentioned by @oising) does still not work as the project type does not support.
Specifically I have a problem with scss files which I would like to place below their corresponding html files. But as nesting might be subject to framework and/or personal taste, make it configurable and changeable with that plugin would be great.

**Comment by abpiskunov** [comment]
Nesting rules are predefined now and there no configuration exposed. We put that on hold because of too many changes in Preview 1. We will consider to add it in later milestones.
