### ISSUE TITLE
Immidiate window not work for method local variable

### ISSUE THREAD

**Issue by MohammadAkbari** [aspnet/Tooling#438]
immidiate window and other debugging tools in visual studio work correctly before I upgrade visual studio update 2 rc, after upgrade immidiate window raise error this error
error CS0103: The name 'name' does not exist in the current context
when evaluate local variable that define in method, but method params correctly work.
![f4f6aca6-f5bb-11e5-8ca3-1e6df72beb67](https://cloud.githubusercontent.com/assets/18085318/14131394/f528eaba-f64f-11e5-9831-118e506a181f.PNG)

**Comment by smudge202** [comment]
This isn't particularly well explained, but I'm seeing some wide spread debugging issues since the update (from friends, and [stackoverflow](http://stackoverflow.com/questions/36284093/visual-studio-2015-update-2-rtm-and-rc-debugging-context-not-available#). Is this being tracked in an issue/connect ticket/somewhere?

**Comment by herecydev** [comment]
Can also confirm this: 

- Local variables are broken (hovering has no effect)
- Unable to resolve in immediate window
- Parameters are fine

I raised feedback through VS2015 this morning, but it would seem prudent to get an official response ASAP as this seems incredibly broken and wouldn't surprise me if people are rolling back.

**Comment by joshuapetryk** [comment]
+1 here, having exact same issue where local variables do not exist in current context. This happens on a new Asp.Net 5 project created from template. 

Visual Studio Enterprise 2015
Version 14.0.25123.00 Update 2

ASP.NET and Web Tools 2015 RC1 Update 1 (14.1.20203.0)

**Comment by FabienLavocat** [comment]
@joshuapetryk you save my day! I've been fighting that issue since yesterday it was driving me crazy. Thanks a lot, it works now!

**Comment by StefH** [comment]
Same issue : https://github.com/aspnet/Tooling/issues/439

**Comment by sayedihashimi** [comment]
Sorry to hear that you're running into this. It was a regression with the debugger bits in Update 2.

We have fixed the issue. It should be included in the next Visual Studio Update (different from ASP.NET Core RC2), but it may be possible that this gets released before update 3. I'm looking into it.

TFS: 207744

**Comment by FabienLavocat** [comment]
I still have a few issues with the debugging (after enabling "Use Managed Compatibility Mode").
For example, I can't debug into some part of code of a Class Library Package (from ASP.NET Core), I don't know if it is related to this same bug.
Please, ship a fix before Update 3!

**Comment by sayedihashimi** [comment]
OK we have release an update which should solve this issue, more info at https://msdn.microsoft.com/library/mt695655.aspx. The direct download link is http://go.microsoft.com/fwlink/?LinkID=785969&clcid=0x409.

Please let me know if you have any issues with this fix. I'll close this now, but if you still run into this please comment and I will re-open.

**Comment by StefH** [comment]
Thank you for the fix, it works for me.

**Comment by FabienLavocat** [comment]
It works for me too. Thanks.
I still have an issue with the debugging of a Class Library (Package) that is loaded into my main project, but I will create a different bug in GitHub.
