### ISSUE TITLE
Visual Studio - Hangs while editing dependencies in project.json

### ISSUE THREAD

**Issue by allenmoatallen** [aspnet/Tooling#519]
I am running Visual Studio 2015 Update 2 with the new RC2 tooling. Since upgrading to RC2, Visual Studio has issues editing the dependencies of the `project.json` file. It takes a couple minutes for the text you entered to start showing up in the window. While this is happening the IDE appears to hang but never becomes unresponsive (just can't click or do anything else).

I've had to drop to the CLI tools and VS Code to work around it.

**Comment by tonysneed** [comment]
I am experiencing the same issue. If I try to add a dependency by typing it, VS 2015 will otfen hang with a white screen. Sometimes it comes back after a while, other times I need to kill the VS process.

**Comment by Tynamix** [comment]
Same for me here! +1

**Comment by janpieterz** [comment]
I'm experiencing the same. Just a thought, are you guys by any chance using custom Nuget sources (possibly Visual Studio Team Services feeds?). If so, could you try by removing them temporarily?

I noticed when removing these the process is a lot smoother. This made me think it might 'hang' on the requests to those external feeds. Annoyingly, it sometimes really takes a long time or indeed never returns.

**Comment by allenmoatallen** [comment]
@janpieterz Besides an in-house feed the rest of mine I believe are the defaults. What is in your list so I can verify?

**Comment by janpieterz** [comment]
The 'smooth' one has: 
```xml
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
```

The not so smooth one adds one local one (file system) and three VSTS feeds.

**Comment by allenmoatallen** [comment]
Is there any reason to keep the `v2` feed if you have `v3`?

**Comment by janpieterz** [comment]
Don't know to be honest, but for me it doesn't seem to cause this specific issue (or others) to keep it in.

**Comment by allenmoatallen** [comment]
I only have the `v3` feed and a local (file system) one for all projects as well as those same two listed in a project specific NuGet.Config and I get the 'hanging' behavior.

**Comment by sayedihashimi** [comment]
TFS: 224847
I've added this to our internal TFS, we will reply back here soon.

**Comment by davidmdem** [comment]
I am experiencing this as well and am using a local network feed.  It seems to be better when the local feed is removed.  

In case it's relevant, I came to the issues section because I don't seem to be able to resolve any dependencies from this feed.  They show up in the Package Manager and I select and click Install, but am immediately presented with a dependency could not be resolved message.  

This same package can be successfully added to a boilerplate MVC 5 application.

**Comment by Gonkers** [comment]
When I edit anywhere in my project.json visual studio doesn't become "unresponsive" but stops accepting all input and the process must be killed. I have removed all local nuget feeds and has not helped. Below is the output of the about dialog.

Once I ran devenv in /safemode I was able to edit the project.json without issue. I have not yet been able to narrow down what is causing the issue. I assume it's an extension, but not yet confirmed.
---------------------------------------------
Only nuget feed: https://api.nuget.org/v3/index.json

Microsoft Visual Studio Professional 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

Microsoft Visual Studio Tools for Applications 2015   00322-50050-00435-AA028
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-50050-00435-AA028
Microsoft Visual Basic 2015

Visual C# 2015   00322-50050-00435-AA028
Microsoft Visual C# 2015

Visual C++ 2015   00322-50050-00435-AA028
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-50050-00435-AA028
Windows Phone SDK 8.0 - ENU

Add Empty File   1.9
Gives the ability to add an empty file with any extension and starting with a dot

ASP.NET and Web Tools 2015.1   14.1.20512.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9   14.0.20316.0
Azure App Service Tools v2.9

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Bundler & Minifier   1.9.157
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Color Theme Designer   1.0
Designer for creating new color themes

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

File Nesting   1.0
Automatically nest files based on file name and enables developers to nest and unnest any file manually

File Nesting   2.5.60
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Image Optimizer   3.6.89
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft .NET Core Tools (Preview 1)   14.1.20512.0
Microsoft .NET Core Tools (Preview 1)

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40114.1

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.174
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

Package Installer   1.7.79
Makes it easier, faster and more convenient than ever to install Bower, npm, JSPM, TSD, Typings and NuGet packages to any project

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Analysis Services   13.0.1601.5
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1601.5

SQL Server Data Tools   14.0.60525.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1601.5
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1601.5

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.31.0
TypeScript tools for Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Web Analyzer   1.7.77
Provides static analysis directly in Visual Studio for JavaScript, TypeScript, JSX, CSS and more

Web Compiler   1.11.315
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.2   2.0.214
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

**Comment by nbarbettini** [comment]
I'm still experiencing this issue in Visual Studio 2015 Update 3. I thought this bug was fixed in Preview 2 - is that not the same thing as Update 3?

**Comment by barrytang** [comment]
cc @mlorbetske, @DamianEdwards 

@nbarbettini, you will need to install the latest .NET Core Preview2 tooling from https://www.microsoft.com/net/core#windows as well.

**Comment by nbarbettini** [comment]
@barrytang Already installed those - from that page, I installed VS 2015 Update 3 and the .NET Core for VS tooling package.

**Comment by barrytang** [comment]
@mlorbetske, can you take a look?

**Comment by mlorbetske** [comment]
@nbarbettini could you copy in the information from your VS instance's Help -> About please?

**Comment by nbarbettini** [comment]
@mlorbetske This info?

```
Microsoft Visual Studio Professional 2015
Version 14.0.25421.03 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

Visual Basic 2015   00322-40000-00000-AA459
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA459
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA459
Microsoft Visual C++ 2015

Visual F# 2015   00322-40000-00000-AA459
Microsoft Visual F# 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Multiline Search and Replace   1.6
Adds multiline search and replace functionality to Visual Studio.

NCrunch   
Continuous Testing Tool for .NET
Copyright © 2010-2015 Remco Software Ltd

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PowerModeOptionsPackage Extension   1.1.5
PowerModeOptionsPackage Visual Stuido Extension Detailed Info

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40621.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40621.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40621.00
Profiling support for Python projects.

Sandcastle Help File Builder   SHFB
Visual Studio integration for the Sandcastle Help File Builder.
Copyright © 2011-2015, Eric Woodruff, All Rights Reserved.
https://GitHub.com/EWSoftware/SHFB

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

StopOnFirstBuildError   1.0
StopOnFirstBuildError

Stops a solution build immediately after a project has failed to build.

http://tech.einaregilsson.com/2011/01/06/stop-build-on-first-error-in-visual-studio-2010/

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript   1.8.34.0
TypeScript tools for Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Universal Windows Apps   14.0.25420.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   4.1.0.530 (2e39740)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.1.0.71 (4e27558)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   9.8.0.323 (39ebb77)
Visual Studio extension to enable development for Xamarin.iOS.
```

**Comment by mlorbetske** [comment]
@nbarbettini that was quick, thanks! Unfortunately, this seems to be a known issue with R# 2016.1 but is fixed with 2016.2 EAP5 according to this R# dev https://twitter.com/zhuravlik26/status/748214609044246528

**Comment by nbarbettini** [comment]
Ah, interesting. Thanks!

**Comment by Grinderofl** [comment]
Still an issue for me. I've noticed that visual studio freezes for longer the more you manage to type prior to freezing... it's as if it's enqueueing multiple searches for packages for intellisense and waiting for all of them to return. Could probably be verified with some fiddler spying.

**Comment by nathan-alden** [comment]
I am running ReSharper 2016.3 EAP 4 and I've noticed this issue consistently since at least 2016.2.

**Comment by Uninspiriert** [comment]
I am running ReSharper Ultimate 2016.2.2, had the same issue. What solved it for me, was to use native Visual Studio IntelliSense instead of the extended ReSharper one for JSON files (ReSharper -> Options -> IntelliSense -> General).

**Comment by Mike-EEE** [comment]
Your suggestion worked for me, @Uninspiriert.  The totally promised "lit up experience" of project.json has totally blown me away... at how it managed to lock my instance of Visual Studio despite being a product pushing towards twenty years of existence. Seems like this type of bug simply will not die despite being around since VS's inception.  At the very least, you would think something more pleasant would have been devised by this point.  I mean, just marvel at this error message:

![](https://content.screencast.com/users/Mike-EEEE/folders/Jing/media/3c28af29-f883-4732-88ef-1ae866d571ad/2017-02-26_1054.png)

Report ... what?  TO WHO?  AND HOW????  CLICKING IT DOES NOTHING?!?!?!?!  ALL THE CONFUSE!!!

WE CAN DO BETTER TEAM!!! I KNOW WE CAN!!! :) :) :)
