### ISSUE TITLE
VisualStudio Bower - Package Wrong Version Downloads

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Tooling#575]
The bower tooling doesn't use the specified version when installing packages http://stackoverflow.com/questions/37584520/bootstrap-3-3-6-jquery-2-2-4-version-exception

jquery#2.2.4 downloads 3.0.0-rc ?

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231140&fullScreen=false&_a=edit">231140</a>

**Comment by bgl3317** [comment]
Is there any update on this issue?  It's causing my team a lot problems since the default tooling experience with Bower is breaking Bootstrap straight out of the gate.

**Comment by AlekseyMartynov** [comment]
@bgl3317 check my suggestion at http://stackoverflow.com/a/38460014

**Comment by grahamehorner** [comment]
their are more issues with vs bower packages not install as the case is incorrect eg. PACE can't be found as the package name is pace.  even after an install of git from the official site and clearing the cache these issues remain.

**Comment by JakeSimmons89** [comment]
Any Update when this will be fixed.

**Comment by SimplerSoftware** [comment]
This issue caused me to start using NPM for everything... which I do like now but what a pain to have to switch mid-way through a project.

**Comment by chapeti** [comment]
Any update on this bug?, very frustrating... :(

**Comment by jvinis** [comment]
Any update ? Hotfix ?

**Comment by denisz1** [comment]
Big bug it is not honoring my prefer version. Bugfix please?

Problem is `bower.cmd` runs `--force-latest`.

**Comment by JonasAxelsson** [comment]
Any update?

**Comment by grahamehorner** [comment]
A work around is to install the command line extension and run bower manually from the command line extension for the project. The work around also allows bower to install packages not displayed in the VS bower extension.

**Comment by jodavis** [comment]
It appears that this was caused by a "fake git.exe", a limited libgit2 wrapper that VS installs to support Bower when Git is not installed on the system. It's possible to work around the issue by installing Git on the system. If full Git is on the %PATH%, VS will pick it up and use it. If it's not on the %PATH%, then the path to Git can be added to Tools->Options->Projects and Solutions->External Web Tools.

The libgit2 wrapper has been removed in VS 2017 RC, in favor of using the minimal Git installation provided for Git-related source control in VS. That version of Git does not exhibit this issue.

For information, the --force-latest flag should not cause Bower to install the latest version of a package. It is supposed to resolve conflicts when two packages require incompatible versions of the same dependency, by choosing the later of the two versions. On the command line, Bower would prompt the user to choose a version. VS doesn't currently have a way to answer the prompt, so --force-latest is used to prevent the Bower restore from becoming blocked indefinitely.

**Comment by denisz1** [comment]
So problem is fixed in NEXT version. Which available, maybe, sometime, next year. LOL.

**Comment by ThisWillDoIt** [comment]
This issue is still present in the VS 2017 RC version released yesterday.
ASP.NET Core 1.1 MVC template comes with jQuery 2.2.0. Going into the "Manage Bower Packages" and selecting to update to jQuery 2.2.4 installs jQuery 3.1.1 instead.

**Comment by Schaussi** [comment]
Same here, just spent hours with testing with 2015 and 2017 RC. E.g. I wanted Bootstrap v3.7 and got v4 alpha.
Anyway, similar to the SO solution, this worked for me in VS 2017 RC (didn't need Git for Windows):

1. bower.json: Make sure the version numbers are correct in there
2. Close VS
3. delete %LOCALAPPDATA%\bower
4. delete content of [yourproject]\wwwroot\lib
5. Re-Open your project with VS
6. Right-click on bower dependencies -> restore
7. Versions should be correct now

**Comment by bendrick92** [comment]
Thank you Schaussi!  I was having the same issue with the newest release of Visual Sutdio 2017.  Clearing the APPDATA\bower and \lib directories worked perfectly.

**Comment by bakgaard** [comment]
It didn't work for me though.
I can make a new project from a template which downloads all the files, then open the bower.json to correct the, e.g., bootstrap version from 3.3.6 to 3.3.7, but then it can't figure out to download the new version.

**Comment by WagnerExpansiva** [comment]
1) I changed bower.json, a wrong camelCase 'jQuery' 

before
```  
"dependencies": {
    "jQuery": "2.2.4", ...
```

after:
```
"dependencies": {
    "jquery": "2.2.4", ...
```

2) Then, I Did this procedure, https://github.com/aspnet/Tooling/issues/575#issuecomment-277696647
